<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="PE-HO-507" failures="1" tests="1" name="Default test" time="108.865" errors="0" timestamp="23 sept 2022 18:19:02 GMT">
  <testcase classname="com.ConsultaDCD.test.RevisarDCDTest" name="RevisarDCDPortalFedepalma" time="99.289">
    <failure type="com.itextpdf.text.DocumentException" message="The document has been closed. You can&amp;apos;t add any Elements.">
      <![CDATA[com.itextpdf.text.DocumentException: The document has been closed. You can't add any Elements.
at com.itextpdf.text.Document.add(Document.java:267)
at utilities.GenerarReportePdf.closeTemplate(GenerarReportePdf.java:181)
at PagObject_demoautomatizacion.BasePage.click(BasePage.java:211)
at PagObject_ConsultaDCD.RevisarDCDPage.RevisarDCD(RevisarDCDPage.java:43)
at com.ConsultaDCD.test.RevisarDCDTest.RevisarDCDPortalFedepalma(RevisarDCDTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RevisarDCDPortalFedepalma -->
=======
<testsuite ignored="5" hostname="PE-HO-274" failures="0" tests="1" name="Default test" time="187.592" errors="0" timestamp="23 sep. 2022 18:31:01 GMT">
  <testcase classname="com.AdministracionUsuariosNuevos.test.BloqueantesUETest" name="QuitarPermisoEmailUE" time="183.492"/>
  <testcase classname="com.AdministracionUsuariosNuevos.test.BloqueantesUETest" name="QuitarPermisoBoqueoUE" time="0.0">
    <ignored/>
  </testcase> <!-- QuitarPermisoBoqueoUE -->
  <testcase classname="com.AdministracionUsuariosNuevos.test.BloqueantesUETest" name="FuncionamientoSinBloqueosUE" time="0.0">
    <ignored/>
  </testcase> <!-- FuncionamientoSinBloqueosUE -->
  <testcase classname="com.AdministracionUsuariosNuevos.test.BloqueantesUETest" name="DesasociarUsuario" time="0.0">
    <ignored/>
  </testcase> <!-- DesasociarUsuario -->
  <testcase classname="com.AdministracionUsuariosNuevos.test.BloqueantesUETest" name="QuitarPermisoFirmaUE" time="0.0">
    <ignored/>
  </testcase> <!-- QuitarPermisoFirmaUE -->
  <testcase classname="com.AdministracionUsuariosNuevos.test.BloqueantesUETest" name="VisualizarContenedorUE" time="0.0">
    <ignored/>
  </testcase> <!-- VisualizarContenedorUE -->
>>>>>>> a5b718a5085655fe616131c9055e168f0b189a6a
</testsuite> <!-- Default test -->
